apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: flaskapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
      tier: backend
  template:
    metadata:
      labels:
        app: flaskapi
        tier: backend
    spec:
      containers:
        - name: flaskapi 
          image: my-flask-api:0.1
          ports:
          - containerPort: 5000
          env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_DB
            value: test
---
apiVersion: v1
kind: Service
metadata:
    name: flaskapi
spec:
    type: LoadBalancer
    ports:
    - port: 8099 
      targetPort: 5000
    selector:
        app: flaskapi
        tier: backend