apiVersion: v1
kind: Service
metadata:
    name: flaskapi
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 5000
    selector:
        app: flaskapi
        tier: backend